GET http://localhost:3000/todos/?search_q=Play

###

GET http://localhost:3000/todos/2/

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###

PUT http://localhost:3000/todos/3/
Content-Type: application/json

{
    "status":"IN PROCESS"
}

###
DELETE http://localhost:3000/todos/8/